[profile.default]
src             = 'contracts'             # The source directory
test            = 'test'                  # The test directory
out             = 'out'                   # The ouput directory
libs            = ['node_modules', 'lib'] # A list of library directories
#solc_version    = '0.7.6'                # Override for the solc version (setting this ignores `auto_detect_solc`). Comment if you need to have multiple solidity versions
optimizer       = true                    # Enable or disable the solc optimizer
optimizer_runs  = 200                     # The number of optimizer runs
verbosity       = 2                       # The verbosity of tests
chainId         = 1                       # The chain for tests

[fmt]
line_length                      = 120           # Specifies the maximum line length where the formatter will try to wrap the line.
tab_width                        = 4            # Number of spaces per indentation level.
bracket_spacing                  = true         # Whether or not to print spaces between brackets.
int_types                        = "long"       # Style of uint/int256 types. Valid values are: "long", "short" or "preserve".
func_attrs_with_params_multiline = true         # If function parameters are multiline then always put the function attributes on separate lines.
quote_style                      = "double"     # Defines the quotation mark style. Valid values are: "double", "single" or "preserve".
number_underscore                = "thousands"  # Style of underscores in number literals. Valid values are: "preserve", "thousands" or "remove".